package com.evn.game.db.dao;

import com.evn.game.db.po.Player;
import com.evn.game.db.po.PlayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerMapper {

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        long countByExample(PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int deleteByExample(PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int insert(Player record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int insertSelective(Player record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        List<Player> selectByExample(PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        Player selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int updateByExampleSelective(@Param("record") Player record, @Param("example") PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int updateByExample(@Param("record") Player record, @Param("example") PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int updateByPrimaryKeySelective(Player record);

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the database table player
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        int updateByPrimaryKey(Player record);
}