package com.evn.game.db.po;

public class Player {

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column player.id
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        private Long id;
        /**
         * This field was generated by MyBatis Generator. This field corresponds to the database column player.name
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        private String name;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column player.id
         * @return  the value of player.id
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        public Long getId() {
                return id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column player.id
         * @param id  the value for player.id
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        public void setId(Long id) {
                this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column player.name
         * @return  the value of player.name
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        public String getName() {
                return name;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column player.name
         * @param name  the value for player.name
         * @mbg.generated  Tue Nov 26 10:46:03 CST 2019
         */
        public void setName(String name) {
                this.name = name;
        }
}